export const CUSTOM_LANGUAGE = {
  js: 'Javascript',
  ts: 'TypeScript',
  json: 'JSON',
  c: 'C',
  cpp: 'C++',
  rust: 'Rust',
  golang: 'Go',
  bash: 'Bash',
  solidity: 'Solidity',
  python: 'Python',
  html: 'HTML',
  css: 'CSS',
  java: 'Java',
  markdown: 'Markdown',
  Sql: 'SQL',
  xml: 'XML',
  swift: 'SWIFT',
  obc: 'Objective-C',
}